version: "3"

services:
  main-nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dhunica_proxypass
    restart: always
    external_links:
      - dh.unica_nginx
      - dhunica_laravel_default
    networks:
      - default
      - dhunica_default
      - dhunica_laravel_default
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./html:/var/www/html
      - ./redirect:/etc/nginx/redirect
      - ./ssl-proof:/var/www/ssl-proof
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/digicertca:/etc/digicertca
      - ./htpassword:/etc/password_custom
    ports:
     - "80:80"
     - "443:443"
    environment:
      NGINX_ERROR_LOG_LEVEL: error

networks:
  dhunica_default:
    external: true
  dhunica_laravel_default:
    external: true